/*
 * The approved logo artwork, as data.
 *
 * Generated by scripts/generate-brand-lockup.mjs from the files named in
 * `source` below. Every coordinate is the artwork's own — the lettering is
 * outlined in the supplied files and is reproduced here unchanged, never set
 * in one of the site's typefaces.
 *
 * Do not edit by hand. Change the file in public/brand and re-run the script.
 *
 * Ajani Healthcare — logo v1. Creator: Olasupo Ajani.
 * © 2026 Ajani Healthcare Limited. https://www.ajanihealthcare.com
 */

export const BRAND_ARTWORK = {
  "lockup": {
    "source": "public/brand/ajani-healthcare-logo-colour-transparent.svg",
    "viewBox": "0 0 840 360",
    "width": 840,
    "height": 360,
    "shapes": [
      {
        "tag": "rect",
        "x": 48,
        "y": 48,
        "width": 264,
        "height": 264,
        "rx": 66,
        "fill": "#0B5351"
      },
      {
        "tag": "path",
        "d": "M18 43 29.6 17h5.2L46 43h-7.2l-2-5H27.4l-2.1 5H18Zm11.7-11h4.8l-2.4-6.3L29.7 32Z",
        "fill": "#FAF8F1",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "circle",
        "cx": 47,
        "cy": 17,
        "r": 5,
        "fill": "#D2AA56",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#0B5351",
        "transform": "translate(352.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M210 540H70V-63C70 -94 59 -105 29 -105C20 -105 13 -104 4 -101V-213C31 -216 65 -218 87 -218C174 -218 210 -182 210 -94ZM210 729H70V604H210Z",
        "fill": "#0B5351",
        "transform": "translate(481.960 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M524 17C500 40 492 56 492 83V383C492 493 417 549 271 549C125 549 49 487 40 362H175C182 418 205 436 274 436C328 436 355 418 355 382C355 364 346 349 331 340C312 330 312 330 243 319L187 309C80 291 28 236 28 139C28 42 93 -23 192 -23C252 -23 306 2 356 54C356 26 359 16 372 0H524ZM355 217C355 136 315 90 244 90C197 90 168 115 168 155C168 197 190 217 248 229L296 238C333 245 339 247 355 255Z",
        "fill": "#0B5351",
        "transform": "translate(532.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M63 540V0H203V324C203 388 247 430 316 430C376 430 406 397 406 333V0H546V362C546 482 481 549 365 549C292 549 243 523 203 462V540Z",
        "fill": "#0B5351",
        "transform": "translate(632.080 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M207 540H67V0H207ZM207 729H67V604H207Z",
        "fill": "#0B5351",
        "transform": "translate(742.060 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#0B5351",
        "transform": "translate(352.000 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#0B5351",
        "transform": "translate(399.557 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#0B5351",
        "transform": "translate(445.408 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 729H80V0H579V125H230Z",
        "fill": "#0B5351",
        "transform": "translate(492.965 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M385 604H598V729H14V604H235V0H385Z",
        "fill": "#0B5351",
        "transform": "translate(537.081 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#0B5351",
        "transform": "translate(581.196 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M682 482C677 545 664 585 633 626C577 700 487 741 378 741C172 741 44 594 44 358C44 123 171 -23 374 -23C556 -23 676 82 685 249H539C529 156 471 103 378 103C262 103 194 197 194 356C194 517 265 613 383 613C470 613 519 571 539 482Z",
        "fill": "#0B5351",
        "transform": "translate(628.753 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#0B5351",
        "transform": "translate(676.310 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 289H402C467 289 495 263 495 203V173C494 154 494 136 494 125C494 56 498 35 516 0H677V27C654 40 645 55 645 87C641 302 637 312 544 352C626 384 667 443 667 532C667 590 647 643 612 679C579 713 533 729 471 729H80V0H230ZM230 414V604H411C454 604 471 600 490 585C508 570 517 545 517 511C517 476 508 448 490 433C473 419 454 414 411 414Z",
        "fill": "#0B5351",
        "transform": "translate(723.866 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#0B5351",
        "transform": "translate(771.423 286) scale(0.031 -0.031)"
      }
    ]
  },
  "lockupDark": {
    "source": "public/brand/ajani-healthcare-logo-colour-navy.svg",
    "viewBox": "0 0 840 360",
    "width": 840,
    "height": 360,
    "shapes": [
      {
        "tag": "rect",
        "x": 48,
        "y": 48,
        "width": 264,
        "height": 264,
        "rx": 66,
        "fill": "#0B5351"
      },
      {
        "tag": "path",
        "d": "M18 43 29.6 17h5.2L46 43h-7.2l-2-5H27.4l-2.1 5H18Zm11.7-11h4.8l-2.4-6.3L29.7 32Z",
        "fill": "#FAF8F1",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "circle",
        "cx": 47,
        "cy": 17,
        "r": 5,
        "fill": "#D2AA56",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FAF8F1",
        "transform": "translate(352.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M210 540H70V-63C70 -94 59 -105 29 -105C20 -105 13 -104 4 -101V-213C31 -216 65 -218 87 -218C174 -218 210 -182 210 -94ZM210 729H70V604H210Z",
        "fill": "#FAF8F1",
        "transform": "translate(481.960 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M524 17C500 40 492 56 492 83V383C492 493 417 549 271 549C125 549 49 487 40 362H175C182 418 205 436 274 436C328 436 355 418 355 382C355 364 346 349 331 340C312 330 312 330 243 319L187 309C80 291 28 236 28 139C28 42 93 -23 192 -23C252 -23 306 2 356 54C356 26 359 16 372 0H524ZM355 217C355 136 315 90 244 90C197 90 168 115 168 155C168 197 190 217 248 229L296 238C333 245 339 247 355 255Z",
        "fill": "#FAF8F1",
        "transform": "translate(532.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M63 540V0H203V324C203 388 247 430 316 430C376 430 406 397 406 333V0H546V362C546 482 481 549 365 549C292 549 243 523 203 462V540Z",
        "fill": "#FAF8F1",
        "transform": "translate(632.080 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M207 540H67V0H207ZM207 729H67V604H207Z",
        "fill": "#FAF8F1",
        "transform": "translate(742.060 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#FAF8F1",
        "transform": "translate(352.000 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#FAF8F1",
        "transform": "translate(399.557 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FAF8F1",
        "transform": "translate(445.408 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 729H80V0H579V125H230Z",
        "fill": "#FAF8F1",
        "transform": "translate(492.965 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M385 604H598V729H14V604H235V0H385Z",
        "fill": "#FAF8F1",
        "transform": "translate(537.081 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#FAF8F1",
        "transform": "translate(581.196 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M682 482C677 545 664 585 633 626C577 700 487 741 378 741C172 741 44 594 44 358C44 123 171 -23 374 -23C556 -23 676 82 685 249H539C529 156 471 103 378 103C262 103 194 197 194 356C194 517 265 613 383 613C470 613 519 571 539 482Z",
        "fill": "#FAF8F1",
        "transform": "translate(628.753 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FAF8F1",
        "transform": "translate(676.310 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 289H402C467 289 495 263 495 203V173C494 154 494 136 494 125C494 56 498 35 516 0H677V27C654 40 645 55 645 87C641 302 637 312 544 352C626 384 667 443 667 532C667 590 647 643 612 679C579 713 533 729 471 729H80V0H230ZM230 414V604H411C454 604 471 600 490 585C508 570 517 545 517 511C517 476 508 448 490 433C473 419 454 414 411 414Z",
        "fill": "#FAF8F1",
        "transform": "translate(723.866 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#FAF8F1",
        "transform": "translate(771.423 286) scale(0.031 -0.031)"
      }
    ]
  },
  "lockupInverse": {
    "source": "public/brand/ajani-healthcare-logo-white-transparent.svg",
    "viewBox": "0 0 840 360",
    "width": 840,
    "height": 360,
    "shapes": [
      {
        "tag": "rect",
        "x": 50.244,
        "y": 50.244,
        "width": 259.512,
        "height": 259.512,
        "rx": 63.756,
        "fill": "none",
        "stroke": "#FFFFFF",
        "strokeWidth": 4.488
      },
      {
        "tag": "path",
        "d": "M18 43 29.6 17h5.2L46 43h-7.2l-2-5H27.4l-2.1 5H18Zm11.7-11h4.8l-2.4-6.3L29.7 32Z",
        "fill": "#FFFFFF",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "circle",
        "cx": 47,
        "cy": 17,
        "r": 5,
        "fill": "#FFFFFF",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FFFFFF",
        "transform": "translate(352.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M210 540H70V-63C70 -94 59 -105 29 -105C20 -105 13 -104 4 -101V-213C31 -216 65 -218 87 -218C174 -218 210 -182 210 -94ZM210 729H70V604H210Z",
        "fill": "#FFFFFF",
        "transform": "translate(481.960 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M524 17C500 40 492 56 492 83V383C492 493 417 549 271 549C125 549 49 487 40 362H175C182 418 205 436 274 436C328 436 355 418 355 382C355 364 346 349 331 340C312 330 312 330 243 319L187 309C80 291 28 236 28 139C28 42 93 -23 192 -23C252 -23 306 2 356 54C356 26 359 16 372 0H524ZM355 217C355 136 315 90 244 90C197 90 168 115 168 155C168 197 190 217 248 229L296 238C333 245 339 247 355 255Z",
        "fill": "#FFFFFF",
        "transform": "translate(532.000 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M63 540V0H203V324C203 388 247 430 316 430C376 430 406 397 406 333V0H546V362C546 482 481 549 365 549C292 549 243 523 203 462V540Z",
        "fill": "#FFFFFF",
        "transform": "translate(632.080 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M207 540H67V0H207ZM207 729H67V604H207Z",
        "fill": "#FFFFFF",
        "transform": "translate(742.060 208) scale(0.18 -0.18)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#FFFFFF",
        "transform": "translate(352.000 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#FFFFFF",
        "transform": "translate(399.557 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FFFFFF",
        "transform": "translate(445.408 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 729H80V0H579V125H230Z",
        "fill": "#FFFFFF",
        "transform": "translate(492.965 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M385 604H598V729H14V604H235V0H385Z",
        "fill": "#FFFFFF",
        "transform": "translate(537.081 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M507 331V0H657V729H506V456H218V729H68V0H218V331Z",
        "fill": "#FFFFFF",
        "transform": "translate(581.196 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M682 482C677 545 664 585 633 626C577 700 487 741 378 741C172 741 44 594 44 358C44 123 171 -23 374 -23C556 -23 676 82 685 249H539C529 156 471 103 378 103C262 103 194 197 194 356C194 517 265 613 383 613C470 613 519 571 539 482Z",
        "fill": "#FFFFFF",
        "transform": "translate(628.753 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M501 147 549 0H703L451 729H285L26 0H179L228 147ZM460 272H270L365 557Z",
        "fill": "#FFFFFF",
        "transform": "translate(676.310 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M230 289H402C467 289 495 263 495 203V173C494 154 494 136 494 125C494 56 498 35 516 0H677V27C654 40 645 55 645 87C641 302 637 312 544 352C626 384 667 443 667 532C667 590 647 643 612 679C579 713 533 729 471 729H80V0H230ZM230 414V604H411C454 604 471 600 490 585C508 570 517 545 517 511C517 476 508 448 490 433C473 419 454 414 411 414Z",
        "fill": "#FFFFFF",
        "transform": "translate(723.866 286) scale(0.031 -0.031)"
      },
      {
        "tag": "path",
        "d": "M229 314H578V439H229V604H606V729H79V0H624V125H229Z",
        "fill": "#FFFFFF",
        "transform": "translate(771.423 286) scale(0.031 -0.031)"
      }
    ]
  },
  "symbol": {
    "source": "public/brand/ajani-symbol-colour-transparent.svg",
    "viewBox": "0 0 360 360",
    "width": 360,
    "height": 360,
    "shapes": [
      {
        "tag": "rect",
        "x": 48,
        "y": 48,
        "width": 264,
        "height": 264,
        "rx": 66,
        "fill": "#0B5351"
      },
      {
        "tag": "path",
        "d": "M18 43 29.6 17h5.2L46 43h-7.2l-2-5H27.4l-2.1 5H18Zm11.7-11h4.8l-2.4-6.3L29.7 32Z",
        "fill": "#FAF8F1",
        "transform": "translate(48 48) scale(4.125)"
      },
      {
        "tag": "circle",
        "cx": 47,
        "cy": 17,
        "r": 5,
        "fill": "#D2AA56",
        "transform": "translate(48 48) scale(4.125)"
      }
    ]
  }
};
